---

- name: configure maintenance page service
  include: maintenance.yml

- name: ensure haproxy config folder
  file: path=/opt/haproxy/config/ state=directory mode=0755

- name: ensure haproxy config file
  template: src="haproxy.cfg.j2" dest=/opt/haproxy/config/haproxy.cfg mode=0644

- name: ensure haproxy container running
  docker_container:
    name: haproxy
    image: haproxy:2.1.3-alpine
    state: started
    restart: no
    log_driver: json-file
    log_options:
      max-size: 50m
      max-file: "10"
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "/opt/haproxy/config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    ports:
      - "80:80"
      - "443:443"
      - "6443:6443"

- name: restart haproxy
  docker_container: name=haproxy restart=yes

